scraper: DefaultScraper
urls:
  - "https://news.sabay.com.kh"
engine: requests
middlewares:
  - name: HeaderMiddleware
    params:
      user_agent: "Mozilla/5.0 (Custom Agent)"
  - name: RetryMiddleware
    params:
      retries: 5
      delay: 2
parser:
  name: DefaultParser
exporter:
  name: JsonExporter
  params:
    output_path: "./output/data.json"