name: Publish Python Package

# Trigger on version tags like v1.0.0, v2.1.3, etc.
on:
  push:
    tags:
      "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name:  Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
        
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Build package
        run: python -m build
      
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
      
      - name: Success message
        run: echo "Package published successfully for tag ${{ github.ref }}"
